### ISSUE TITLE
When I try to convert an .mp4 file/buffer with full type, it does not work

### ISSUE THREAD

**Issue by chikof** [AlenVelocity/wa-sticker-formatter#11]
![image](https://user-images.githubusercontent.com/53100578/129759522-48f660cf-079c-47cf-bacd-2e5819b2f8f6.png)

I was looking the code, and I give up 🏳.

**Comment by PrajjwalDatir** [comment]
commenting for notifications.

**Comment by erickythierry** [comment]
Version 4.x started using ffmpeg to format the input file to .webp type, but it doesn't work well for gif and mp4 files (version 3.x only modifies the metadata of webp files)
