### ISSUE TITLE
Gif/video sticker is not being Formatted into sticker 

### ISSUE THREAD

**Issue by bilal-08** [AlenVelocity/wa-sticker-formatter#14]
when using with image wsf perfectly works with it.
but if i try video or gif to make sticker the sticker does not send output.

**Comment by bilal-08** [comment]
I found Termux Package of libvips
that can be executed with
``` pkg install libvips```
But The error is same...
Should i use flag -g

**Comment by erickythierry** [comment]
I'm having the same problem here. my solution was rollback for 3.x version

**Comment by Helvio88** [comment]
Fixed in 4.4.1
