### ISSUE TITLE
How to use on gif/video image? 

### ISSUE THREAD

**Issue by ThisMe124** [AlenVelocity/wa-sticker-formatter#30]

**Comment by AlenSaito1** [comment]
Same as Images, the `Sticker` constructor and `createSticker()` can accept a video file, buffer, or URL as the first argument

**Comment by ThisMe124** [comment]
> Same as Images, the `Sticker` constructor and `createSticker()` can accept a video file, buffer, or URL as the first argument

Why is my Video/gif getting corrupted?  Or you could say the picture is messed up

**Comment by AlenSaito1** [comment]
This will be fixed relatively soon.

ttps://github.com/AlenSaito1/wa-sticker-formatter/pull/29

**Comment by ThisMe124** [comment]
> This will be fixed relatively soon.
> 
> #29

Error like This
![IMG_20211209_062923](https://user-images.githubusercontent.com/88891071/145298512-83f12f46-c465-4fdc-ba10-977803aaa9a6.jpg)
