### ISSUE TITLE
sticker from video or gif is generated with a strange effect

### ISSUE THREAD

**Issue by erickythierry** [AlenVelocity/wa-sticker-formatter#31]
### the sticker looks like the example below:
![ezgif com-gif-maker](https://user-images.githubusercontent.com/11170366/145875710-98c95a3b-c060-40cf-9329-60160755d9f4.gif)

### my code:
```
const sticker = new Sticker(buffer, {
    pack: 'thierry', // The pack name
    author: 'bot thierry', // The author name
    type: StickerTypes.FULL, // The sticker type
    categories: ['🤩', '🎉'], // The sticker category
    id: '1234', // The sticker id
    quality: 50, // The quality of the output file
})
await sticker.toFile('./static/sticker.webp')
```

**Comment by AlenSaito1** [comment]
https://github.com/AlenSaito1/wa-sticker-formatter/pull/29 Future fix

**Comment by noxzym** [comment]
any update for this? also, my phone can't play animate sticker that was generated

**Comment by AlenVelocity** [comment]
This issue was fixed a while ago. 

You can try decreasing the quality. Whatsapp will only play animated stickers if the size is 1MB or less
