### ISSUE TITLE
Error: cannot find ffmpeg

### ISSUE THREAD

**Issue by AdamRoyn** [AlenVelocity/wa-sticker-formatter#42]
When I'm going to make a sticker in mp4 format this error appears in the console
```
Error: Cannot find ffmpeg
```
Even though I already installed ffmpeg with
```
npm i fluent-ffmpeg
```

**Comment by aidulcandra** [comment]
+1

**Comment by aidulcandra** [comment]
Actually I have managed to figure it out
This really depends on your environment. Where do you run your program? Does it support ffmpeg?

If it does, try to find the path to the ffmpeg executable first.

If you can't find it, you may have to use this module: ffmpeg-static, this will install ffmpeg in your system and it can give you the path to it. Just follow the instructions: [here](https://www.npmjs.com/package/ffmpeg-static)

After you get the path, set it to the environment system:
`process.env.FFMPEG_PATH = pathToFFMPEG`
