### ISSUE TITLE
any way to just set the exif data?

### ISSUE THREAD

**Issue by erickythierry** [AlenVelocity/wa-sticker-formatter#43]
I'm using version 3.6 to just define the pack and author of the sticker. I have my own function that converts to webp with a nice performance. is there any way to only use this functionality in the most current version of the lib?

I need the most current function because it runs on ARM machines

**Comment by AlenVelocity** [comment]
Yes, you can use the exported `Exif` class like so
```ts
import { Exif } from 'wa-sticker-formatter'

const webp; /* your image*/
const webpWithExif = await new Exif({ pack: 'name' }).add(webp)
```
